const CATEGORIES_ACTION_TYPES = {
  CATEGORIES_FETCH: "categories/CATEGORIES_FETCH",
  CATEGORIES_SUCCESS: "categories/CATEGORIES_SUCCESS",
  CATEGORIES_FAILED: "categories/CATEGORIES_FAILED",
};
export default CATEGORIES_ACTION_TYPES;
