const PRODUCTS_ACTION_TYPES = {
  PRODUCTS_FETCH: "products/PRODUCTS_FETCH",
  PRODUCTS_SUCCESS: "products/PRODUCTS_SUCCESS",
  PRODUCTS_FAILED: "products/PRODUCTS_FAILED",
};
export default PRODUCTS_ACTION_TYPES;
